### ISSUE TITLE
Compatibility on .Net.core

### ISSUE THREAD

**Issue by M2Key** [codetuner/Arebis.Common#4]
What about a portage on asp net core?

**Comment by codetuner** [comment]
I'd love to do the port, but unfortunately I have a head full of ideas and plans but no time to execute them... Be noted that some features rely on advanced functionality of .NET such as ContextBoundObjects. I'm not sure this will work the same on .NET Core.

Probably I will do a .NET Core version once I'm working on a major project on that platform, but I will not have time to attempt a feature-by-feature conversion.
